source 'https://rubygems.org'

gem 'sinatra', '1.4.7'
gem 'sinatra-flash', '0.3.0', require: 'sinatra/flash'
gem 'bcrypt-ruby', '3.1.5'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'config_env'
gem 'rbnacl-libsodium'
gem 'protected_attributes'
gem 'haml'
gem 'tux'
gem 'json'
gem 'warden', '1.2.6'
gem 'shotgun', '0.9.1'

gem 'dm-core', '1.2.1'
gem 'dm-sqlite-adapter', '1.2.0'
gem 'dm-migrations', '1.2.0'
gem 'dm-serializer', '1.2.2'
gem 'dm-timestamps', '1.2.0'
gem 'dm-transactions', '1.2.0'
gem 'dm-types', '1.2.2'
gem 'dm-validations', '1.2.0'
